version: '3.9'
services:
  nextjs:
    build: ./
    restart: always
    networks:
      - net
    ports:
       - "3000:3000"
    command: "yarn run start"
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - net
networks:
  net:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.220.0/24