version: '3.8'
services:
  nextjs:
    build: ./
    restart: always
    networks:
      - net
    command: "yarn run start"
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: ./nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - net
networks:
    net:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.220.0/24